### ISSUE TITLE
fatjar requires FACEBOOK_CLIENT_ID and FACEBOOK_CLIENT_SECRET

### ISSUE THREAD

**Issue by cnacorrea** [modalityone/modality#12]
**Exception thrown in case I start the fatjar without Facebook info**
I set up the database, start the fatjar, it seems to apply everything OK, but at the end of the initialization process it throws an exception saying it can't resolve the Facebook associated variables.

**To Reproduce**
1. Run the fatjar without any variables set for Facebook SSO/integration
2. Wait for the exception to pop up

**Expected behavior**
If Facebook variables are not defined, the integration should not be enabled and the code for it skipped?

**Screenshots**
![image](https://user-images.githubusercontent.com/688358/209046365-3366d0c4-5075-40e3-abf6-b514fa685014.png)

**Comment by salmonb** [comment]
hi @cnacorrea,

The NPE thrown here was actually not related to the previous warnings saying that FACEBOOK_CLIENT_ID and FACEBOOK_CLIENT_SECRET were not resolved (which is fine, this just prevents the Facebook SSO to work, this shouldn't prevent the server to start).

This NPE (that was crashing the server initialisation) occurred on your server (and not mine) due to a random initialisation sequence (the code was initialising some providers returned by the Java Service API which returns the providers in a random order). In your case, the Facebook SSO configuration was initialised before the HTTP configuration, and this created a problem, because the Facebook default configuration refers to the variable HTTP_SERVER_ORIGIN which is set by the HTTP configuration.

I fixed the problem by ensuring that the HTTP configuration is processed first. In addition, even if the HTTP_SERVER_ORIGIN variable couldn't be resolved for any reason, this will now produce a warning and not a NPE.

The fix is actually in the WebFX Stack code, not Modality. But if you rebuild the fat jar again, it should take the new WebFX snapshot version.

Can you please rebuild the fat jar and let me know if this fixes the problem?

**Comment by cnacorrea** [comment]
This was fixed a long time ago :-) Closing this issue.
